include: package:pedantic/analysis_options.yaml

analyzer:
  enable-experiment:
    - non-nullable
linter:
  rules:
    - cancel_subscriptions
    - close_sinks
    - hash_and_equals
    - iterable_contains_unrelated_type
    - list_remove_unrelated_type
    - test_types_in_equals
    - unrelated_type_equality_checks
    - valid_regexps
    - public_member_api_docs
